### ISSUE TITLE
Stressng plugin fails to run in workflow

### ISSUE THREAD

**Issue by tsebastiani** [arcalot/arcaflow-plugin-stressng#9]
## Describe the bug
When the plugin is run from inside a workflow apparently schema validation fails with this error
```
Workflow execution failed (failed to read plugin schema from quay.io/arcalot/arcaflow-plugin-stressng:latest (invalid schema (Validation failed for 'steps' -> '[workload]' -> 'input' -> 'objects' -> '[StressNGParams]' -> 'properties' -> '[items]' -> 'type' -> 'items' -> 'types' -> '[cpu]': Missing discriminator field 'type_id' in 'map[id:CpuStressorParams]')))
```
Everytime that the workflow is run the input dataclass in the exception changes randomly (MqStressorParams, VmStressorParams etc.)

## To reproduce

The input structure passed seems to not affect this behaviour because the issue happens before retrieving the input schema from the container.

Example workflow
```
input:
  root: RootObject
  objects:
    RootObject:
      id: RootObject
      properties:
        kubeconfig:
          display:
            description: The complete kubeconfig file as a string
            name: Kubeconfig file contents
          type:
            type_id: string
          required: true
        node_selector:
            display:
              description: kubernetes node name where the plugin must be deployed
            type:
              type_id: map
              values:
                type_id: string
              keys:
                type_id: string
            required: true

steps:
  kubeconfig:
    plugin: quay.io/arcalot/arcaflow-plugin-kubeconfig:latest
    input:
      kubeconfig: !expr $.input.kubeconfig
  stressng:
    plugin: quay.io/arcalot/arcaflow-plugin-stressng:latest
    step: workload
    input: 
      StressNGParams:
        timeout: 20s
        cleanup: "true"
        items:
          - stressor: cpu
            cpu_count: 2
            cpu_method: "all"
    deploy:
      type: kubernetes
      connection: !expr $.steps.kubeconfig.outputs.success.connection
      pod:
        metadata:
          namespace: default
          labels:
            arcaflow: stressng
        spec:
          nodeSelector: !expr $.input.node_selector
          pluginContainer:
            imagePullPolicy: Always
output:
  stressng: !expr $.steps.stressng.outputs.success
```
